version: "3.9"
services:
  postgres:
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: users
    ports:
    - 32574:5432